* Fix pool life-time issue with apr_socket_addr_get(), resulting in a memory   leak in Apache mod_proxy. * Under Linux, if configure does not detect POSIX semaphores due to /dev/shm   not being mounted, abort the build. Closes: #591286
git-svn-id: svn+ssh://svn.debian.org/svn/pkg-apache/trunk/apr@1222 01b336ce-410b-0410-9a02-a0e7f243c266

diff --git a/debian/rules b/debian/rules
--- a/debian/rules
+++ b/debian/rules
@@ -81,6 +81,20 @@ ifeq (hurd, $(DEB_BUILD_ARCH_OS))
 	# multicast not supported on Hurd
 	sed -i '/HAVE_STRUCT_IPMREQ/ d' $(BUILDDIR)/include/arch/unix/apr_private.h
 endif
+ifeq (linux, $(DEB_BUILD_ARCH_OS))
+	if grep -q APR_HAS_POSIXSEM_SERIALIZE.*0 $(BUILDDIR)/include/apr.h ;\
+	then \
+		echo "WARNING: This is Linux but configure did not detect POSIX semaphores." ;\
+		if [ "$(stat -c '%d' /dev/shm)" = "$(stat -c '%d' /dev)" ] ;\
+		then \
+			echo "ERROR: POSIX semaphores not usable and /dev/shm not mounted." ;\
+			echo "ERROR: Aborting." ;\
+			echo "HINT: If you are using pbuilder or cowbuilder, add /dev/shm to BINDMOUNTS" ;\
+			echo "HINT: in pbuilderrc" ;\
+			exit 1 ;\
+		fi ;\
+	fi
+endif
 
 build: patch-stamp build-stamp
 
